import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-white text-lg leading-relaxed bg-[#111111] `}
      >
        <main className="flex flex-col w-screen h-screen overflow-y-auto overflow-x-hidden "
         >
          <Navbar />
          <div className="flex h-full max-h-screen w-full flex-col bg-cover px-6 ">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
